# Generated by Django 5.2.17 on 2026-09-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', 'name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
    ]
