# Generated by Django 5.2.17 on 2026-09-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_course_options_alter_department_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Hod_name',
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='hod_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
